name: 'Sync Branches'
description: 'GitHub Action to seamlessly synchronize changes across branches'
author: 'Ian Woodard'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'git-pull-request'
  color: 'blue'

# Define your inputs here.
inputs:
  source-branch:
    description: 'Source Branch'
    required: true
  target-branch:
    description: 'Target Branch'
    required: true
  commit-message:
    description: 'Commit Message'
    required: true
  github-token:
    description: 'GitHub Token'
    required: true

# Define your outputs here.
outputs:
  pull-request-url:
    description: 'URL of the pull request'
  pull-request-number:
    description: 'Number of the pull request'

runs:
  using: node20
  main: dist/index.js
